name: Windows

on:
  workflow_dispatch:
    inputs:
      node-version:
        description: 'Node.js version to run tests'
        required: true
        default: 20
        type: number

jobs:
  tests:
    name: Node.js ${{inputs.node-version}}
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - uses: actions/setup-node@v3
      with:
        node-version: ${{inputs.node-version}}
    - id: npm-cache
      run: echo "dir=$(npm config get cache)" >> $GITHUB_OUTPUT
    - uses: actions/cache@v3
      with:
        path: ${{steps.npm-cache.outputs.dir}}
        key: windows-latest-node-${{hashFiles('**/package-lock.json')}}
        restore-keys: |
          windows-latest-node-
          windows-latest-
    - run: |
        npm ci
        npm run build --if-present
        npm test
        node tests/test-sample.js
